export const moviesMockData = [
  {
    adult: false,
    backdrop_path: '/backdrop1.jpg',
    genre_ids: [28, 12],
    id: 1,
    original_language: 'en',
    original_title: 'Iron Man',
    overview: 'A billionaire builds a high-tech suit to fight crime.',
    popularity: 100.5,
    poster_path: '/ironman.jpg',
    release_date: '2008-05-02',
    title: 'Iron Man',
    video: false,
    vote_average: 7.9,
    vote_count: 18000,
  },
  {
    adult: false,
    backdrop_path: '/backdrop2.jpg',
    genre_ids: [80, 18],
    id: 2,
    original_language: 'en',
    original_title: 'The Dark Knight',
    overview:
      'Batman sets out to dismantle the remaining criminal organizations in Gotham.',
    popularity: 120.3,
    poster_path: '/darkknight.jpg',
    release_date: '2008-07-18',
    title: 'The Dark Knight',
    video: false,
    vote_average: 8.5,
    vote_count: 23000,
  },
];
